test: chronogramme.o
	$(CC) -o test chronogramme.o

chronogramme.o: chronogramme.c
	$(CC) -O -Wall -W -ansi -c chronogramme.c

#################################################################################

clean:
	rm -f *~ *.o
	rm -f test