test: echeance.o
	$(CC) -o test echeance.o

echeance.o: echeance.c
	$(CC) -O -Wall -W -ansi -c echeance.c

#################################################################################

clean:
	rm -f *~ *.o
	rm -f test